version: "3.8"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: keycloak
    restart: on-failure:3
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - 9090:8080
    networks:
      - docker-net
    volumes:
      - keycloak:/opt/keycloak/data/:rw
    command: start-dev

networks:
  docker-net:
    name: docker-net
    external: false

volumes:
  keycloak:
    name: keycloak
    external: false