quarkus:
  http:
    port: 8080

quarkus:
  keycloak:
    policy-enforcer:
      paths:
        public:
          paths: /q
          enforcement-mode: DISABLED
  oidc:
    auth-server-url: ${KEYCLOAK_URL:http://localhost:9090/realms/caja-ande}
    token:
      issuer: ${KEYCLOAK_TOKEN_ISSUER:any}
    client-id: ${KEYCLOAK_CLIENT_ID:back}
    credentials:
      secret: ${KEYCLOAK_CLIENT_SECRET:xxx}
    tls:
      verification: none
