name: caja-ande-backend

networks:
  docker-net:
    name: docker-net
    external: true

services:

  backend:
    image: caja-ande/quarkus:1.0.0-SNAPSHOT
    hostname: backend
    container_name: backend
    environment:
      KEYCLOAK_URL: http://keycloak:8080/realms/caja-ande
      KEYCLOAK_TOKEN_ISSUER: http://localhost:9090/realms/caja-ande
      KEYCLOAK_CLIENT_ID: back
      KEYCLOAK_CLIENT_SECRET: bOiBIwUNVJreDMuOIlbE54Z47YGjIxVh
    ports:
      - 8080:8080
    networks:
      - docker-net
